### ISSUE TITLE
Lista de grupos para trabajo final

### ISSUE THREAD

**Issue by lmdiazangulo** [lmdiazangulo/MCFNL2020#3]
1. - Matt. Toni.
2. - José Manuel. Pedro.
3. - José Camacho. Álvaro.
4. - María. Amador.
5. - Juan Pablo. Alex. 
6. - Jorge. Emiliano.

**Comment by PaulFaith** [comment]
Equipo 5: Proposal 9.

**Comment by altemoy28** [comment]
Equipo 3 (José Camacho y Álvaro): propuesta 7 (Calculate a 2D waveguide)

**Comment by Mpedrosab** [comment]
Equipo 4. Proposal 8 (Simulation of a dispersive material)

**Comment by Rumoa** [comment]
Equipo 1.  Proposal 2: FDTD in nonuniform grid

**Comment by lmdiazangulo** [comment]
Equipo 6. Proposal cloaking.

**Comment by lmdiazangulo** [comment]
Equipo 2, Proposal 3: Reflection coefficient of a slightly conductive panel
